-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Users"
(
    "Id" integer NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."Candidates"
(
    "Id" integer NOT NULL,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "NationalId" character(11) NOT NULL,
    "BirthYear" integer NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."Employers"
(
    "Id" integer NOT NULL,
    "CompanyName" character varying(50) NOT NULL,
    "WebSiteName" character varying(50) NOT NULL,
    "PhoneNumber" character(10) NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."Jobs"
(
    "Id" integer NOT NULL,
    "JobId" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 999 CACHE 1 ),
    "JobName" character varying(50) NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."Employees"
(
    "Id" integer NOT NULL,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."People"
(
    "Id" integer NOT NULL,
    "Email" character varying(50) NOT NULL,
    "Password" character varying(50) NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."Jobs_Users"
(
    "Jobs_JobId" integer NOT NULL,
    "Users_Id" integer NOT NULL
);

ALTER TABLE public."Candidates"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."Employers"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."Users"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."People" ("Id")
    NOT VALID;


ALTER TABLE public."Employees"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."People" ("Id")
    NOT VALID;


ALTER TABLE public."Jobs_Users"
    ADD FOREIGN KEY ("Users_Id")
    REFERENCES public."Users" ("Id")
    NOT VALID;

END;